//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1_3MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FootBallLeague
    {
        public int MatchID { get; set; }
        public string TeamName1 { get; set; }
        public string TeamName2 { get; set; }
        public string Status1 { get; set; }
        public string WinningTeam { get; set; }
        public int Points { get; set; }
    }
}
